# Generated by Django 5.2.1 on 2025-05-27 15:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_language_userlanguage_user_languages'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('active', 'Active'), ('inactive', 'Inactive')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_activity', models.DateTimeField(blank=True, null=True)),
                ('user1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_user1', to=settings.AUTH_USER_MODEL)),
                ('user1_learns', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_learned_by_user1', to='users.language')),
                ('user1_teaches', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_taught_by_user1', to='users.language')),
                ('user2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_user2', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user1', 'user2')},
            },
        ),
        migrations.CreateModel(
            name='MatchRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, help_text='Optional message from sender')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_match_requests', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_match_requests', to=settings.AUTH_USER_MODEL)),
                ('sender_learns', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learned_in_requests', to='users.language')),
                ('sender_teaches', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taught_in_requests', to='users.language')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('sender', 'receiver')},
            },
        ),
        migrations.CreateModel(
            name='PotentialMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compatibility_score', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('potential_partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='potential_for', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='potential_matches', to=settings.AUTH_USER_MODEL)),
                ('user_learns', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learned_in_matches', to='users.language')),
                ('user_teaches', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taught_in_matches', to='users.language')),
            ],
            options={
                'ordering': ['-compatibility_score', '-created_at'],
                'unique_together': {('user', 'potential_partner')},
            },
        ),
    ]
