# Generated by Django 5.2.1 on 2025-05-28 11:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0003_videoroom_expected_participants'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videoroom',
            name='expected_participants',
        ),
        migrations.CreateModel(
            name='CallStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('call_stats', models.JSONField(default=dict, help_text='Raw call statistics from client')),
                ('duration_seconds', models.IntegerField(blank=True, help_text='Call duration in seconds', null=True)),
                ('connection_quality', models.CharField(blank=True, help_text='Overall connection quality', max_length=50)),
                ('video_quality', models.CharField(blank=True, help_text='Video resolution and quality', max_length=50)),
                ('disconnections', models.IntegerField(default=0, help_text='Number of disconnections during call')),
                ('reconnect_attempts', models.IntegerField(default=0, help_text='Number of reconnection attempts')),
                ('connection_stability_score', models.FloatField(blank=True, help_text='0-1 stability score', null=True)),
                ('overall_quality_score', models.FloatField(blank=True, help_text='0-1 overall quality score', null=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to='chats.videoroom')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to='chats.callsession')),
            ],
            options={
                'verbose_name_plural': 'Call Statistics',
                'ordering': ['-created_at'],
            },
        ),
    ]
