# Generated by Django 5.2.1 on 2025-05-28 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0004_remove_videoroom_expected_participants_and_more'),
    ]

    operations = [
    ]
