# Generated by Django 5.2.1 on 2025-05-28 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0007_remove_networkqualitylog_room_and_more'),
    ]

    operations = [
    ]
