# Generated by Django 5.2.1 on 2025-05-28 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0002_callinvitation_userpresence'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoroom',
            name='expected_participants',
            field=models.IntegerField(default=2, help_text='Number of expected participants in this room'),
        ),
    ]
