# Generated by Django 5.2.1 on 2025-05-28 11:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0005_add_call_statistics'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkQualityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('bandwidth_up', models.FloatField(blank=True, help_text='Upload bandwidth in kbps', null=True)),
                ('bandwidth_down', models.FloatField(blank=True, help_text='Download bandwidth in kbps', null=True)),
                ('latency', models.FloatField(blank=True, help_text='Round trip time in ms', null=True)),
                ('jitter', models.FloatField(blank=True, help_text='Jitter in ms', null=True)),
                ('packet_loss', models.FloatField(blank=True, help_text='Packet loss percentage', null=True)),
                ('audio_quality', models.CharField(blank=True, max_length=20)),
                ('video_quality', models.CharField(blank=True, max_length=20)),
                ('connection_state', models.CharField(blank=True, max_length=20)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='network_logs', to='chats.videoroom')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='network_logs', to='chats.callsession')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='CallFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_rating', models.IntegerField(choices=[(1, '1 - Very Poor'), (2, '2 - Poor'), (3, '3 - Fair'), (4, '4 - Good'), (5, '5 - Excellent')], help_text='Overall call experience')),
                ('audio_quality_rating', models.IntegerField(blank=True, choices=[(1, '1 - Very Poor'), (2, '2 - Poor'), (3, '3 - Fair'), (4, '4 - Good'), (5, '5 - Excellent')], null=True)),
                ('video_quality_rating', models.IntegerField(blank=True, choices=[(1, '1 - Very Poor'), (2, '2 - Poor'), (3, '3 - Fair'), (4, '4 - Good'), (5, '5 - Excellent')], null=True)),
                ('connection_stability_rating', models.IntegerField(blank=True, choices=[(1, '1 - Very Poor'), (2, '2 - Poor'), (3, '3 - Fair'), (4, '4 - Good'), (5, '5 - Excellent')], null=True)),
                ('issues', models.JSONField(default=list, help_text='List of issues experienced during call')),
                ('comments', models.TextField(blank=True, help_text='Additional feedback or comments')),
                ('would_recommend', models.BooleanField(blank=True, help_text='Would recommend this service', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='chats.videoroom')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='chats.callsession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='call_feedback', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('room', 'user')},
            },
        ),
    ]
