# Generated by Django 5.2.1 on 2025-05-28 11:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0006_networkqualitylog_callfeedback'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='networkqualitylog',
            name='room',
        ),
        migrations.RemoveField(
            model_name='networkqualitylog',
            name='session',
        ),
        migrations.AlterUniqueTogether(
            name='callfeedback',
            unique_together={('session', 'user')},
        ),
        migrations.AddField(
            model_name='callfeedback',
            name='audio_quality',
            field=models.IntegerField(blank=True, choices=[(1, '1 - Very Poor'), (2, '2 - Poor'), (3, '3 - Average'), (4, '4 - Good'), (5, '5 - Excellent')], null=True),
        ),
        migrations.AddField(
            model_name='callfeedback',
            name='connection_stability',
            field=models.IntegerField(blank=True, choices=[(1, '1 - Very Poor'), (2, '2 - Poor'), (3, '3 - Average'), (4, '4 - Good'), (5, '5 - Excellent')], null=True),
        ),
        migrations.AddField(
            model_name='callfeedback',
            name='partner_rating',
            field=models.IntegerField(blank=True, choices=[(1, '1 - Very Poor'), (2, '2 - Poor'), (3, '3 - Average'), (4, '4 - Good'), (5, '5 - Excellent')], null=True),
        ),
        migrations.AddField(
            model_name='callfeedback',
            name='report_inappropriate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='callfeedback',
            name='technical_issues',
            field=models.TextField(blank=True, help_text='Report any technical issues'),
        ),
        migrations.AddField(
            model_name='callfeedback',
            name='video_quality',
            field=models.IntegerField(blank=True, choices=[(1, '1 - Very Poor'), (2, '2 - Poor'), (3, '3 - Average'), (4, '4 - Good'), (5, '5 - Excellent')], null=True),
        ),
        migrations.AddField(
            model_name='callfeedback',
            name='would_call_again',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='callsession',
            name='disconnection_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='callsession',
            name='end_notes',
            field=models.TextField(blank=True, help_text='Additional notes about call ending'),
        ),
        migrations.AddField(
            model_name='callsession',
            name='end_reason',
            field=models.CharField(blank=True, choices=[('normal', 'Normal end'), ('user_hangup', 'User hung up'), ('partner_hangup', 'Partner hung up'), ('connection_lost', 'Connection lost'), ('timeout', 'Session timeout'), ('technical_issue', 'Technical issue'), ('emergency', 'Emergency end')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='callsession',
            name='ended_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ended_calls', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='callsession',
            name='max_participants',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='callfeedback',
            name='comments',
            field=models.TextField(blank=True, help_text='Additional comments about the call'),
        ),
        migrations.AlterField(
            model_name='callfeedback',
            name='overall_rating',
            field=models.IntegerField(choices=[(1, '1 - Very Poor'), (2, '2 - Poor'), (3, '3 - Average'), (4, '4 - Good'), (5, '5 - Excellent')]),
        ),
        migrations.AlterField(
            model_name='callfeedback',
            name='session',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='chats.callsession'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='callsession',
            name='status',
            field=models.CharField(choices=[('starting', 'Starting'), ('active', 'Active'), ('ended', 'Ended'), ('failed', 'Failed'), ('interrupted', 'Interrupted')], default='starting', max_length=20),
        ),
        migrations.DeleteModel(
            name='CallStatistics',
        ),
        migrations.DeleteModel(
            name='NetworkQualityLog',
        ),
        migrations.RemoveField(
            model_name='callfeedback',
            name='audio_quality_rating',
        ),
        migrations.RemoveField(
            model_name='callfeedback',
            name='connection_stability_rating',
        ),
        migrations.RemoveField(
            model_name='callfeedback',
            name='issues',
        ),
        migrations.RemoveField(
            model_name='callfeedback',
            name='room',
        ),
        migrations.RemoveField(
            model_name='callfeedback',
            name='video_quality_rating',
        ),
        migrations.RemoveField(
            model_name='callfeedback',
            name='would_recommend',
        ),
    ]
