# Generated by Django 5.2.1 on 2025-05-28 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0008_auto_20250528_1139'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='callsession',
            name='disconnection_count',
        ),
        migrations.RemoveField(
            model_name='callsession',
            name='end_notes',
        ),
        migrations.RemoveField(
            model_name='callsession',
            name='end_reason',
        ),
        migrations.RemoveField(
            model_name='callsession',
            name='ended_by',
        ),
        migrations.RemoveField(
            model_name='callsession',
            name='max_participants',
        ),
        migrations.AlterField(
            model_name='callsession',
            name='status',
            field=models.CharField(choices=[('starting', 'Starting'), ('active', 'Active'), ('ended', 'Ended'), ('failed', 'Failed')], default='starting', max_length=20),
        ),
        migrations.DeleteModel(
            name='CallFeedback',
        ),
    ]
