# Generated by Django 5.2.1 on 2025-05-28 12:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0009_remove_callsession_disconnection_count_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='callsession',
            name='average_video_quality',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='callsession',
            name='disconnection_count',
            field=models.IntegerField(default=0, help_text='Number of disconnections during call'),
        ),
        migrations.AddField(
            model_name='callsession',
            name='end_notes',
            field=models.TextField(blank=True, help_text='Additional notes about call ending'),
        ),
        migrations.AddField(
            model_name='callsession',
            name='end_reason',
            field=models.CharField(blank=True, choices=[('normal', 'Normal end'), ('user_hangup', 'User hung up'), ('partner_hangup', 'Partner hung up'), ('connection_lost', 'Connection lost'), ('timeout', 'Session timeout'), ('technical_issue', 'Technical issue'), ('emergency', 'Emergency end'), ('network_failure', 'Network failure')], help_text='Reason for call ending', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='callsession',
            name='ended_by',
            field=models.ForeignKey(blank=True, help_text='User who ended the call', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ended_calls', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='callsession',
            name='max_participants',
            field=models.IntegerField(default=0, help_text='Maximum participants during call'),
        ),
        migrations.AddField(
            model_name='callsession',
            name='network_issues_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='callsession',
            name='total_data_transferred',
            field=models.BigIntegerField(default=0, help_text='Total data in bytes'),
        ),
    ]
