# Generated by Django 5.2.1 on 2025-05-28 16:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0010_callsession_average_video_quality_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='callinvitation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='callinvitation',
            name='expires_at',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='callinvitation',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AddIndex(
            model_name='callinvitation',
            index=models.Index(fields=['receiver', 'status', 'expires_at'], name='pending_invitations_idx'),
        ),
        migrations.AddIndex(
            model_name='callinvitation',
            index=models.Index(fields=['status', 'created_at'], name='cleanup_invitations_idx'),
        ),
        migrations.AddIndex(
            model_name='callinvitation',
            index=models.Index(fields=['caller', 'status'], name='sent_invitations_idx'),
        ),
    ]
