# Generated by Django 5.2.1 on 2025-06-16 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0012_chatroom_chatmessage_typingstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpresence',
            name='last_activity',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
